### ISSUE TITLE
Gamma

### ISSUE THREAD

**Issue by 1973AReece** [2187Nick/thinkscript#12]
As of last week my gamma study for the options chain stopped working and showing zero values for the 0DTE options. Still working on longer dated. Then I tried some of yours and the same thing. I have checked with two other people and they also are getting no value for the 0DTEs now. Is this what you are seeing? Any idea why its no longer working? Thanks

This is the code that I was originally using before trying yours. 
plot data = if IsPut() then gamma() * -100 * open_interest() else gamma() * 100 * open_interest();

assignbackgroundcolor(if AbsValue(data) >= 3000 then createcolor(255,0,0) else if AbsValue(data) >= 2000 then createcolor(255,255,0) else color.black);

data.assignvaluecolor(if AbsValue(data) > 2000 then color.black else color.current);

**Comment by 2187Nick** [comment]
Hey mate.  We noticed the same issue. A couple people contacted TOS support about it. So they are aware.

The issue is that the built in option functions no longer work for 0dte.

Script to test:

```
addlabel(1, gamma());
```

![image](https://github.com/user-attachments/assets/b678b076-a9a5-4b4a-a15d-913ee9b11d85)
